import uuid
import django.db.models.deletion
from django.db import migrations,models

def perms(apps,schema_editor):
 P=apps.get_model("authorization","Permission")
 for code,action,name in (("fashion.sale.view","sale.view","View fashion sales"),("fashion.sale.manage","sale.manage","Manage fashion sales")): P.objects.update_or_create(code=code,defaults={"module":"fashion","action":action,"name":name})
class Migration(migrations.Migration):
 dependencies=[("authorization","0003_add_i18n_permissions"),("catalog","0003_model_material_requirements"),("customers","0001_initial"),("internationalization","0001_initial"),("measurements","0002_customer_measurement_history"),("organizations","0003_international_settings")]
 operations=[
  migrations.CreateModel(name="Quotation",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("number",models.CharField(max_length=64)),("status",models.CharField(choices=[("draft","Draft"),("sent","Sent"),("accepted","Accepted"),("rejected","Rejected"),("expired","Expired")],default="draft",max_length=16)),("valid_until",models.DateField(blank=True,null=True)),("notes",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="quotations",to="organizations.company")),("currency",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="quotations",to="internationalization.currency")),("customer",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="quotations",to="customers.customer")),("organization",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="quotations",to="organizations.organization"))]),
  migrations.CreateModel(name="Order",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("number",models.CharField(max_length=64)),("status",models.CharField(choices=[("draft","Draft"),("confirmed","Confirmed"),("cancelled","Cancelled")],default="draft",max_length=16)),("delivery_date",models.DateField(blank=True,null=True)),("event_date",models.DateField(blank=True,null=True)),("confirmed_at",models.DateTimeField(blank=True,null=True)),("cancelled_at",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="fashion_orders",to="organizations.company")),("customer",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="fashion_orders",to="customers.customer")),("organization",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="fashion_orders",to="organizations.organization")),("quotation",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="orders",to="sales.quotation"))]),
  migrations.CreateModel(name="QuotationLine",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("description",models.CharField(max_length=255)),("quantity",models.DecimalField(decimal_places=4,default=1,max_digits=14)),("unit_price",models.DecimalField(decimal_places=4,max_digits=14)),("discount_rate",models.DecimalField(decimal_places=4,default=0,max_digits=7)),("fashion_model",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="quotation_lines",to="catalog.fashionmodel")),("model_variant",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="quotation_lines",to="catalog.fashionmodelvariant")),("quotation",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="lines",to="sales.quotation"))]),
  migrations.CreateModel(name="OrderLine",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("description",models.CharField(max_length=255)),("quantity",models.DecimalField(decimal_places=4,default=1,max_digits=14)),("unit_price",models.DecimalField(decimal_places=4,max_digits=14)),("measurement_snapshot",models.JSONField(blank=True,default=dict)),("measurement_source_version",models.PositiveIntegerField(blank=True,null=True)),("fashion_model",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="order_lines",to="catalog.fashionmodel")),("measurement_set",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="order_lines",to="measurements.measurementset")),("model_variant",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="order_lines",to="catalog.fashionmodelvariant")),("order",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="lines",to="sales.order"))]),
  migrations.AddConstraint(model_name="quotation",constraint=models.UniqueConstraint(fields=("organization","number"),name="quotation_unique_number_org")),migrations.AddConstraint(model_name="order",constraint=models.UniqueConstraint(fields=("organization","number"),name="fashion_order_unique_number_org")),migrations.RunPython(perms,migrations.RunPython.noop)]
